### ISSUE TITLE
--failover deactivates failover

### ISSUE THREAD

**Issue by hobofan** [jedisct1/edgedns#1]
Hi there, I am using EdgeDNS in resolver mode with 2 upstream servers. One is 8.8.8.8, the other one is a public Route53 server. The Route53 server only acts as an authoritative server and doesn't resolve queries to public records like facebook.com.

Previously I ran bind9 or dnsmasq, in a failover mode, where the Route53 server was queried, and after that 8.8.8.8, so I tried to run EdgeDNS the same way. However when I activate the `--failover` flag, only queries that can be answered by the first DNS server in the list will resolve successfully. When I just leave out `--failover` it works as wanted, but I don't know if it should.

Could it by that the `--failover` logic is the wrong way round?

**Comment by jedisct1** [comment]
Hi,

With `--failover`, queries are always sent to the first upstream server, unless it is unresponsive. If that happens, it then tries the next ones in order.

When a server returns a `NXDOMAIN` response, this is considered as a perfectly valid and authoritative response. So it is not going to tag the server as broken, and fall back to the next one.

EdgeDNS may not be a good fit for your scenario. Either all the set of upstream should be recursive servers, or it should be authoritative servers.

**Comment by hobofan** [comment]
How does it come that it works in non-failover mode then? Shouldn't that just load balance the query to the upstream servers, which would result in some responses being empty. Instead the lookup is successfull every time (even with restarts to clear the cache).

**Comment by jedisct1** [comment]
In non-failover mode, the queries are indeed load balanced. When a query for a non-authoritative zone is received by the authoritative server, it returns an error, not `NXDOMAIN` (rather a `REFUSED` code). In that situation, edgedns retries with another resolver.

**Comment by hobofan** [comment]
Thanks for the explanations! Makes sense to me now.
