### ISSUE TITLE
Meetup talk?

### ISSUE THREAD

**Issue by erickt** [jedisct1/edgedns#2]
Hi @jedisct1! It's been a while. Interested in talking about edgedns at a rust Bay Area meetup?

**Comment by jedisct1** [comment]
Hi Erick!

Yep, it's been a while! I miss these early Rust meetups at the SF Mozilla office.

I'd love to talk about EdgeDNS and Flowgger. Unfortunately, I don't live in the Bay Area any more.

So unless I have an opportunity to go to SF in a foreseeable future, this is a talk I can only give at a Rust Paris meetup.

**Comment by erickt** [comment]
If Ben happy to host you remotely, or I can hook you up with the rust Paris folks: @pnkfelix :)

**Comment by pnkfelix** [comment]
@jedisct1 are you already on the Rust Paris meetup group? 

We have a meetup this coming Monday:

  https://www.meetup.com/Rust-Paris/events/234528214/

**Comment by jedisct1** [comment]
Hi Felix,

I'm down. I'll do a talk about EdgeDNS and how we use Rust at OVH.

See you there!

**Comment by jedisct1** [comment]
Done!
