### ISSUE TITLE
compile error with rustc 1.12.1

### ISSUE THREAD

**Issue by ben-han-cn** [jedisct1/edgedns#3]
run cargo install --git https://github.com/jedisct1/edgedns with rustc version 1.12.1 get following errors:

error[E0554]: #[feature] may not be used on the stable release channel
 --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/main.rs:3:1
  |
3 | #![feature(integer_atomics)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/resolver.rs:630:21
    |
630 |     let socket_fd = socket(AddressFamily::Inet,
    |                     ^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/resolver.rs:638:21
    |
638 |     let socket_fd = socket(AddressFamily::Inet6,
    |                     ^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/resolver.rs:646:5
    |
646 |     fcntl(sock, F_SETFL(O_NONBLOCK))?;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/resolver.rs:654:30
    |
654 |         SocketAddr::V4(_) => socket_udp_v4()?,
    |                              ^^^^^^^^^^^^^^^^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/resolver.rs:655:30
    |
655 |         SocketAddr::V6(_) => socket_udp_v6()?,
    |                              ^^^^^^^^^^^^^^^^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/resolver.rs:657:5
    |
657 |     set_nonblock(socket_fd)?;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/resolver.rs:658:5
    |
658 |     setsockopt(socket_fd, sockopt::ReuseAddr, &true)?;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/resolver.rs:659:5
    |
659 |     setsockopt(socket_fd, sockopt::ReusePort, &true)?;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/resolver.rs:661:5
    |
661 |     bind(socket_fd, &nix_addr)?;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/tcp_listener.rs:184:25
    |
184 |         let peer_addr = tcp_stream.peer_addr()?.ip();
    |                         ^^^^^^^^^^^^^^^^^^^^^^^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/tcp_listener.rs:375:9
    |
375 |         event_loop.register(&mio_listener,
    |         ^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/udp_listener.rs:112:21
    |
112 |     let socket_fd = socket(AddressFamily::Inet,
    |                     ^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/udp_listener.rs:120:21
    |
120 |     let socket_fd = socket(AddressFamily::Inet6,
    |                     ^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/udp_listener.rs:131:30
    |
131 |         SocketAddr::V4(_) => socket_udp_v4()?,
    |                              ^^^^^^^^^^^^^^^^

error: the `?` operator is not stable (see issue #31436)
   --> /home/vagrant/.cargo/git/checkouts/edgedns-1959b48f5350304c/master/src/udp_listener.rs:132:30
    |
132 |         SocketAddr::V6(_) => socket_udp_v6()?,
    |                              ^^^^^^^^^^^^^^^^

error: aborting due to 16 previous errors

**Comment by jody-frankowski** [comment]
@ben-han-cn You should use rust nightly as the documentation points out.
Compilation works fine with rustc version 1.14.0-nightly.

**Comment by jedisct1** [comment]
Yes, it requires rust-nightly for now.

**Comment by ShibbyContinuum** [comment]
For others reading the issues with trying to install edgedns just use git clone and rustup run nightly cargo build as per usual.  cargo install --git https://github.com/jedisct1/edgedns fails because cargo install doesn't bother with different branches.
