### ISSUE TITLE
Panics when network is unreachable

### ISSUE THREAD

**Issue by f1n3c0n3** [jedisct1/edgedns#7]
When using EdgeDNS in "resolver" mode, it's not uncommon that network connectivity will fail. When it does, a DNS query causes EdgeDNS to panic; specifically, the unwraps at resolver.rs:462 and resolver.rs:501 fail.

I would have simply submitted a PR changing the two instances to ignore errors, but I'm not sure if this is the appropriate error-handling strategy. Certainly the error need not be fatal, but I'm not sure if there's logging that should be done.

Thanks!

**Comment by jedisct1** [comment]
Thanks for reporting this. The `unwrap()` here is indeed a bit too brutal. Not logging that specific failure is probably okay, but it may be a good opportunity to add new metrics regarding protocol-independent network/system errors.

I'm going to work on that soon. Thanks for the heads up!

**Comment by jedisct1** [comment]
Temporary fix in 0e808e5cd8bcc5fe673d7cd56b6e434820fb5ff0

Thanks!
