### ISSUE TITLE
Compile error on Ubuntu 17.04

### ISSUE THREAD

**Issue by ookangzheng** [jedisct1/edgedns#9]
I using Vultr Ubuntu 17.04 64bit, Rust latest version
below is the compile error msg
<img width="898" alt="screen shot 2017-05-02 at 01 08 54" src="https://cloud.githubusercontent.com/assets/6301735/25586890/081ead68-2ed4-11e7-94ea-da093f1396e1.png">

**Comment by jedisct1** [comment]
Please use releases. The development tree is only suitable for development. It may not work at all. And it's designed to work only on rust-nightly.

If you are using rust-stable, add `--no-default-features` to the `cargo` command as `nightly` is enabled by default.
